In [1]:
import pandas as pd
from sportsipy.ncaaf.teams import Teams
teams = Teams(year=2011)
df = teams.dataframes
df['year'] = 2011
yearly_dfs = []
yearly_dfs.append(df)

In [3]:
teams = Teams(year=2012)
df = teams.dataframes
df['year'] = 2012
yearly_dfs.append(df)

In [8]:
teams = Teams(year=2013)
df = teams.dataframes
df['year'] = 2013
yearly_dfs.append(df)

In [9]:
teams = Teams(year=2014)
df = teams.dataframes
df['year'] = 2014
yearly_dfs.append(df)

In [10]:
teams = Teams(year=2015)
df = teams.dataframes
df['year'] = 2015
yearly_dfs.append(df)

In [29]:
teams = Teams(year=2016)
df = teams.dataframes
df['year'] = 2016
yearly_dfs.append(df)

In [30]:
teams = Teams(year=2017)
df = teams.dataframes
df['year'] = 2017
yearly_dfs.append(df)

In [31]:
teams = Teams(year=2018)
df = teams.dataframes
df['year'] = 2018
yearly_dfs.append(df)

In [32]:
teams = Teams(year=2019)
df = teams.dataframes
df['year'] = 2019
yearly_dfs.append(df)

In [33]:
teams = Teams(year=2020)
df = teams.dataframes
df['year'] = 2020
yearly_dfs.append(df)

In [34]:
teams = Teams(year=2021)
df = teams.dataframes
df['year'] = 2021
yearly_dfs.append(df)

In [40]:
cfb = pd.concat(yearly_dfs)

In [56]:
import re
def get_school_name(x):
    school = re.findall("[-A-Za-z ]+[A-Za-z()&]* ", x)
    return school[0].rstrip()

In [57]:
rankings_dfs = []
for year in range(2011, 2022):
    filename = 'ap_rankings_' + str(year) + '.xlsx'
    rankings = pd.read_excel(filename)
    rankings['year'] = year
    rankings = rankings[rankings['Date'] == 'Final']
    rankings['school_name'] = rankings['School'].apply(get_school_name)
    rankings = rankings[['Rk', 'school_name', 'year']]
    rankings_dfs.append(rankings)
ap_rankings = pd.concat(rankings_dfs)

In [84]:
data = cfb.merge(ap_rankings, how='left', left_on=['name', 'year'], right_on = ['school_name', 'year'])
data.columns

Index(['abbreviation', 'conference', 'conference_losses',
       'conference_win_percentage', 'conference_wins', 'first_downs',
       'opponents_first_downs', 'first_downs_from_penalties',
       'opponents_first_downs_from_penalties', 'fumbles_lost',
       'opponents_fumbles_lost', 'games', 'interceptions',
       'opponents_interceptions', 'losses', 'name', 'pass_attempts',
       'opponents_pass_attempts', 'pass_completion_percentage',
       'opponents_pass_completion_percentage', 'pass_completions',
       'opponents_pass_completions', 'pass_first_downs',
       'opponents_pass_first_downs', 'pass_touchdowns',
       'opponents_pass_touchdowns', 'pass_yards', 'opponents_pass_yards',
       'penalties', 'opponents_penalties', 'plays', 'opponents_plays',
       'points_against_per_game', 'points_per_game', 'rush_attempts',
       'opponents_rush_attempts', 'rush_first_downs',
       'opponents_rush_first_downs', 'rush_touchdowns',
       'opponents_rush_touchdowns', 'rush_yards', 'opponents_rush_yards',
       'rush_yards_per_attempt', 'opponents_rush_yards_per_attempt',
       'simple_rating_system', 'strength_of_schedule', 'turnovers',
       'opponents_turnovers', 'win_percentage', 'wins', 'yards',
       'opponents_yards', 'yards_from_penalties',
       'opponents_yards_from_penalties', 'yards_per_play',
       'opponents_yards_per_play', 'year', 'ranking', 'Rk', 'school_name'],
      dtype='object')

In [86]:
data = data.drop(['ranking', 'school_name'], axis=1)
data.to_csv('CFBData.csv')

,abbreviation,conference,conference_losses,conference_win_percentage,conference_wins,first_downs,opponents_first_downs,first_downs_from_penalties,opponents_first_downs_from_penalties,fumbles_lost,...,win_percentage,wins,yards,opponents_yards,yards_from_penalties,opponents_yards_from_penalties,yards_per_play,opponents_yards_per_play,year,Rk
0,CLEMSON,acc,2,0.75,6,22.5,20.2,1.3,1.6,0.9,...,0.714,10,440.8,394.4,40.1,50.1,5.8,5.6,2011,22.0
1,FLORIDA-STATE,acc,3,0.625,5,18.9,15.8,1.5,1.8,0.5,...,0.692,9,369.2,275.0,67.3,47.5,5.9,4.2,2011,23.0
2,WAKE-FOREST,acc,3,0.625,5,20.2,19.8,1.2,1.7,0.3,...,0.462,6,367.8,397.8,43.5,46.2,5.2,5.6,2011,NaN
3,NORTH-CAROLINA-STATE,acc,4,0.5,4,18.4,17.7,1.7,0.8,1.0,...,0.615,8,344.8,354.9,33.8,46.8,4.9,5.3,2011,NaN
4,BOSTON-COLLEGE,acc,5,0.375,3,15.9,19.7,0.9,0.9,0.8,...,0.333,4,298.8,394.3,34.5,38.5,4.7,5.6,2011,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1398,LOUISIANA-LAFAYETTE,sun-belt,0,1.0,8,21.4,18.2,1.2,1.6,0.2,...,0.929,13,412.8,340.9,49.0,48.1,6.0,5.1,2021,16.0
1399,TEXAS-STATE,sun-belt,5,0.375,3,20.3,24.9,2.3,1.8,0.7,...,0.333,4,342.3,433.3,57.5,56.4,5.0,5.9,2021,NaN
1400,SOUTH-ALABAMA,sun-belt,6,0.25,2,19.0,18.2,1.6,1.6,0.8,...,0.417,5,367.7,355.8,43.8,55.7,5.2,5.5,2021,NaN
1401,LOUISIANA-MONROE,sun-belt,6,0.25,2,18.6,22.3,2.5,0.9,0.5,...,0.333,4,328.5,453.2,32.6,57.8,4.6,6.4,2021,NaN
1402,ARKANSAS-STATE,sun-belt,7,0.125,1,21.6,22.5,2.9,1.4,0.4,...,0.167,2,397.2,506.0,50.2,68.8,5.5,7.2,2021,NaN

In [88]:
data.to_csv('CFBData.csv',index=False)